### ISSUE TITLE
Bug in weights for ILP

### ISSUE THREAD

**Issue by the-mysh** [yoyololicon/kamui#6]
Hey, I've noticed what seems to be a typo in [line 104 in `core.py`](https://github.com/yoyololicon/kamui/blob/dev/kamui/core.py#L104).
The `c` which you use as argument to `np.tile` is not defined earlier.
I'd appreciate if you could let me know what the correct argument here is so that I can use weights in my computations.

**Comment by yoyololicon** [comment]
Oh thank you for catching the bug!
I'll push a fix real soon.

**Comment by yoyololicon** [comment]
fix in #7

**Comment by the-mysh** [comment]
Perfect, thanks for addressing this so fast!

**Comment by the-mysh** [comment]
Actually, sorry, something is not quite right still. I'm now getting this `ValueError`:

```
ValueError: Invalid input for linprog: c must be a 1-D array and must not have more than one non-singleton dimension
```

coming from `scipy\optimize\_linprog_util.py:302`.

Maybe it's a question of the dimensionality of the weights I'm passing? My weights are the same shape as the input phase dataset, should I reshape them somehow?

I'm using `scipy` 1.11.1 on Python 3.11.7 if that helps.

**Comment by yoyololicon** [comment]
> Maybe it's a question of the dimensionality of the weights I'm passing? My weights are 2D, the same shape as the input phase dataset, should I reshape them somehow?

Yes, both `differences` and `weights` should be flattened and have the same shape.
Are you using `calculate_k` directly or the wrapper `unwrap_dimensional`? 
I should add a conversion function to pass the weights from the latter to the former.

**Comment by the-mysh** [comment]
I'm using `unwrap_dimensional`, so yeah, I think I can see where the shape mismatch is coming from.
I might switch to the `unwrap_arbitrary` later though, because I often have NaNs in my data and it seems `unwrap_dimensional` is having some trouble with that (it tends to think for a long time and then crash my Jupyter Notebook kernel if there are NaNs)

**Comment by the-mysh** [comment]
Hi @yoyololicon, thanks for all the info. If you find some time to work on the weights shape conversion, I'll be excited to include it in my application!
